# Generated by Django 5.0 on 2024-07-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('highest_education', models.CharField(choices=[('SSC', 'SSC'), ('HSSC', 'HSSC'), ('BS', 'BS'), ('MS', 'MS'), ('PHD', 'PHD')], max_length=50)),
                ('age', models.IntegerField()),
                ('father_name', models.CharField(max_length=50)),
            ],
        ),
    ]
